using MegaCrit.Sts2.Core.Entities.Relics;

namespace Squall.SquallCode.Relics;

//Upgrades summoned GFs and the Magic tokens generated by Draw.
//Checked via GfRegistry.HasSummonUpgrade.
public class SolomonRing() : SquallRelic
{
    public override RelicRarity Rarity => RelicRarity.Rare;
}
